{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mock-identity-provider.fullname" . }}
  labels:
    {{- include "mock-identity-provider.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mock-identity-provider.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8000
          protocol: TCP
    {{- with .Values.networkPolicy.additionalIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    {{- with .Values.networkPolicy.additionalEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
